SampleStore.WebUI/Models/PageLinks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using SampleStore.Domain.Entities;

namespace SampleStore.WebUI.Models
{
  public class PagingInfo
  {
    // Выбранная страница
    public int SelectedPage { get; set; }

    // Число записей на странице
    public int RecordsPerPage { get; set; }

    // Общее число записей
    public int TotalRecords { get; set; }


    // Всего страниц
    public int TotalPages
    {
      get
      {
        return TotalRecords / RecordsPerPage;
      }
    }
  }
}

SampleStore.WebUI/Models/PageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SampleStore.Domain.Entities;
using SampleStore.Domain.Entities.Concrete;

namespace SampleStore.WebUI.Models
{
  public class PageViewModel
  {
    // Список отображаемых продуктов
    public IEnumerable<Product> Products { get; private set; }

    // Информация для отображения ссылок на страницы
    public PagingInfo PagingInfo { get; private set; }

    public PageViewModel(IEnumerable<Product> products,
                         PagingInfo pagingInfo)
    {
      this.PagingInfo = pagingInfo;
      this.Products = products;
    }



  }
}

SampleStore.WebUI/Controllers/HelperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using SampleStore.WebUI.Models;

namespace SampleStore.WebUI.Controllers
{
    // Класс со вспомогательными функциями
    public class HelperController : Controller
    {
      // Метод для отображения списка страниц и текущего выбора
      [ChildActionOnly]
      public ActionResult ShowPageLinks(PagingInfo pagingInfo)
      {
        // Отобразим список
        return PartialView(pagingInfo);
      }

    }
}

SampleStore.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using SampleStore.Domain.Entities.Abstract;
using SampleStore.Domain.Entities;
using SampleStore.Domain.Entities.Concrete;

using SampleStore.WebUI.Models;

namespace SampleStore.WebUI.Controllers
{
    public class HomeController : Controller
    {
      // Репозиторий с данными
      private IProductRepository productsRepo = new ProductRepository();

      // Настройка отображения страниц
      private PagingInfo pagingInfo = new PagingInfo();

      public HomeController()
      {
        pagingInfo.SelectedPage = 0;
        pagingInfo.RecordsPerPage = 2;
        pagingInfo.TotalRecords = productsRepo.Products.Count();
      }

        //
        // GET: /Home/

      public ActionResult Page(int pageNumber = 0)
      {
        pagingInfo.SelectedPage = pageNumber;

        var selectedProducts = productsRepo.Products
                              .Skip(pagingInfo.SelectedPage * pagingInfo.RecordsPerPage)
                              .Take(pagingInfo.RecordsPerPage);

        PageViewModel model = new PageViewModel(selectedProducts,
                                                pagingInfo);

        return View(model);
      }

        public ActionResult Index()
        {
          /*
                    Product[] products = new Product[] 
                    {
                      new Product { ProductId = 0, Name = "USB Drive", Price = 600, Description = "USB-Флеш на 32 Гб."},
                      new Product { ProductId = 1, Name = "HDD Drive", Price = 1600, Description = "HDD 1-Тб."},
                      new Product { ProductId = 2, Name = "iMac", Price = 150000, Description = "Персональный ПК от Apple."},
                      new Product { ProductId = 3, Name = "iPhone", Price = 35000, Description = "Телефон от Apple."}
                    };

                     return View(products.AsEnumerable());
           */
          var selectedProducts = productsRepo.Products.Take(pagingInfo.RecordsPerPage);
          PageViewModel model = new PageViewModel(selectedProducts,
                                                  pagingInfo);

          return View(model);
        }

    }
}

SampleStore.WebUI/Views/Helper/ShowPageLinks.cshtml
@model SampleStore.WebUI.Models.PagingInfo

<table>
    <tr>
        <td class="pageLinksTotal">@Model.TotalPages</td>
        <td>Начало</td>

        <!-- Отобразим несколько видимых страниц -->
        @{
            for (int pageNum = 0;pageNum < Model.TotalPages;pageNum++)
            {
                <td>pageNum</td>
            }
        }

    <td>[@Model.SelectedPage]</td>
        <td>Конец</td>

    </tr>
</table>

SampleStore.WebUI/Views/Helper/childPageLinks.cshtml
@model SampleStore.WebUI.Models.PageLinks


<table>
    <tr>
    <td class="pageLinksTotal">@Model.TotalPages</td>

    @{
        // Число отображенных страниц
        int pagesSeen = 3;
        // Отобразим 
        for (int pageNumber = 0; pageNumber < Model.TotalPages;pageNumber++ )
        {
            
        }
    }
    <td>@Model.TotalPages</td>

    </tr>
</table>

SampleStore.WebUI/Views/Home/Index.cshtml
@model SampleStore.WebUI.Models.PageViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Список товаров:</h2>

@foreach (var p in Model.Products)
{
    <b>@p.Name -</b><blockquote>@p.Description</blockquote><br />
   
    <div>Стоимость @p.Price.ToString("c")</div>
    
    <hr />
}

SampleStore.WebUI/Views/Home/Page.cshtml
@model SampleStore.WebUI.Models.PageViewModel

@{
    ViewBag.Title = "Page";
}

<h1>Текущие настройки модели:</h1>
<table>
    <thead><tr><td>Параметр</td><td>Значение</td></tr></thead>
    <tbody>
        <tr>
            <td>Model.PagingInfo.TotalRecords</td>
            <td>@Model.PagingInfo.TotalRecords</td>
        </tr>
        <tr>
            <td>Model.PagingInfo.RecordsPerPage</td>
            <td>@Model.PagingInfo.RecordsPerPage</td>
        </tr>
        <tr>
            <td>Model.PagingInfo.SelectedPage</td>
            <td>@Model.PagingInfo.SelectedPage</td>
        </tr>
        <tr>
            <td>Model.PagingInfo.TotalPages</td>
            <td>@Model.PagingInfo.TotalPages</td>
        </tr>
    </tbody>
</table>

<hr />

<h2>Page @Model.PagingInfo.SelectedPage</h2>

<span>Отобразим ссылки другие страницы</span>
<br />

@Html.Action("ShowPageLinks", "Helper", new { pagingInfo = Model.PagingInfo })

SampleStore.WebUI/Views/_MainPageLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>THIS IS HEADER</header>
    <div id="mainMenu">HERE IS MAIN MENU</div>
    <h2>_START _OF_BODY_</h2>

    <div>
        @RenderBody()
    </div>
    <h2>_END _OF_BODY_</h2>
    <footer>Here is contacts and so on...</footer>
</body>
</html>